[tool.poetry]
name = "jobapi"
version = "0.1.0"
description = ""
authors = ["rusanov <rusanov.egor@bk.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.31.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
